import { RegleParametreJuridique } from '../types';

export const REGLES_JURIDIQUES_MAROC: RegleParametreJuridique[] = [
  {
    id: 'art-350-anciennete',
    intitule: "Prime d'ancienneté obligatoire",
    domaine: 'droit_travail',
    valeurOuFormule: "2 à 5 ans: 5% | 5 à 12 ans: 10% | 12 à 20 ans: 15% | 20 à 25 ans: 20% | > 25 ans: 25%",
    populationConcernee: "Tous les salariés du secteur privé non agricole",
    dateDebutEffet: "2004-06-08",
    sourceExacte: "Code du Travail marocain (Loi n° 65-99), Article 350",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "La prime d'ancienneté est calculée sur le salaire de base et les majorations pour heures supplémentaires. Elle est acquise de plein droit dès 2 années de service continu ou non dans la même entreprise."
  },
  {
    id: 'cnss-prestations-sociales',
    intitule: "Cotisations CNSS - Prestations Sociales à court et long terme",
    domaine: 'social',
    valeurOuFormule: "Salariale: 4,48% | Patronale: 8,98% (Plafond mensuel de 6 000 MAD)",
    populationConcernee: "Salariés affiliés à la CNSS",
    dateDebutEffet: "2007-01-01",
    sourceExacte: "Dahir portant loi n° 1-72-184 relatif au régime de sécurité sociale",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "Plafonné à 6 000 MAD de salaire brut cotisable. La cotisation salariale maximale est de 268,80 MAD et la cotisation patronale de 538,80 MAD."
  },
  {
    id: 'cnss-allocations-familiales',
    intitule: "Cotisations CNSS - Prestations Familiales",
    domaine: 'social',
    valeurOuFormule: "Patronale exclusive: 6,40% (Déplafonné)",
    populationConcernee: "Employeurs affiliés à la CNSS",
    dateDebutEffet: "2007-01-01",
    sourceExacte: "Dahir portant loi n° 1-72-184",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "A la charge exclusive de l'employeur. Assiette sur la totalité du salaire brut sans plafond."
  },
  {
    id: 'taxe-formation-professionnelle',
    intitule: "Taxe de Formation Professionnelle (OFPPT)",
    domaine: 'social',
    valeurOuFormule: "Patronale exclusive: 1,60% (Déplafonné)",
    populationConcernee: "Employeurs assujettis à la CNSS",
    dateDebutEffet: "1974-01-01",
    sourceExacte: "Loi n° 1-72-183 instituant la taxe de formation professionnelle",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "Financement des actions de formation continue et de l'OFPPT, prélevé mensuellement par la CNSS sur la masse salariale brute."
  },
  {
    id: 'amo-cotisations',
    intitule: "Assurance Maladie Obligatoire (AMO)",
    domaine: 'social',
    valeurOuFormule: "Salariale: 2,26% | Patronale: 4,11% (2,26% + 1,85% solidarité) (Déplafonné)",
    populationConcernee: "Salariés et employeurs assujettis au régime de base",
    dateDebutEffet: "2016-01-01",
    sourceExacte: "Loi n° 65-00 portant Code de la Couverture Médicale de Base",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "Cotisation assise sur l'ensemble de la rémunération brute sans plafonnement."
  },
  {
    id: 'bareme-ir-cgi',
    intitule: "Barème progressif mensuel de l'Impôt sur le Revenu (IR Salarial)",
    domaine: 'fiscal',
    valeurOuFormule: "0-2500: 0% | 2501-4166.67: 10% (déd. 250) | 4167-5000: 20% (déd. 666.67) | 5001-6666.67: 30% (déd. 1166.67) | 6667-15000: 34% (déd. 1433.33) | >15000: 38% (déd. 2033.33)",
    populationConcernee: "Salaires imposables au Maroc",
    dateDebutEffet: "2020-01-01",
    sourceExacte: "Code Général des Impôts (CGI), Article 73-II",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "Calculé sur le salaire Net Imposable mensuel après déduction des cotisations sociales et des frais professionnels. Réduction pour charges de famille: 30 MAD par personne à charge (max 6 personnes soit 180 MAD/mois)."
  },
  {
    id: 'deduction-frais-pros',
    intitule: "Déduction forfaitaire pour frais professionnels",
    domaine: 'fiscal',
    valeurOuFormule: "35% pour brut imposable <= 6 500 MAD (plafond 2 916,67 MAD/mois) ; 25% au-delà (plafond 2 916,67 MAD/mois)",
    populationConcernee: "Salariés du secteur privé",
    dateDebutEffet: "2023-01-01",
    sourceExacte: "Code Général des Impôts (CGI), Article 59",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "Déduction fiscale automatique pour tenir compte des charges professionnelles engagées par le salarié pour l'exercice de son emploi."
  },
  {
    id: 'duree-travail-191h',
    intitule: "Durée légale du travail dans les activités non agricoles",
    domaine: 'droit_travail',
    valeurOuFormule: "2 288 heures par an, soit 44 heures par semaine et 191 heures par mois en moyenne",
    populationConcernee: "Entreprises industrielles, commerciales et de services",
    dateDebutEffet: "2004-06-08",
    sourceExacte: "Code du Travail marocain (Loi 65-99), Article 184",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "Le taux horaire conventionnel de retenue d'absence ou d'heures supplémentaires est obtenu par Salaire de base / 191."
  },
  {
    id: 'heures-supplementaires',
    intitule: "Majoration des heures supplémentaires",
    domaine: 'droit_travail',
    valeurOuFormule: "Jour ouvrable (6h-21h): +25% | Nuit ouvrable (21h-6h): +50% | Repos/Férié jour: +50% | Repos/Férié nuit: +100%",
    populationConcernee: "Salariés effectuant des heures au-delà de 44h/semaine ou 191h/mois",
    dateDebutEffet: "2004-06-08",
    sourceExacte: "Code du Travail marocain (Loi 65-99), Articles 196 à 205",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "Toute heure effectuée au-delà de la durée normale ouvre droit à la rémunération normale majorée du taux légal applicable."
  },
  {
    id: 'motif-cdd-art-16',
    intitule: "Encadrement du Contrat de Travail à Durée Déterminée (CDD)",
    domaine: 'droit_travail',
    valeurOuFormule: "Limité aux cas légaux: remplacement, surcroît exceptionnel, caractère saisonnier, ouverture d'entreprise",
    populationConcernee: "Employeurs et salariés recrutés en CDD",
    dateDebutEffet: "2004-06-08",
    sourceExacte: "Code du Travail marocain (Loi 65-99), Article 16",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "Le CDD ne peut être conclu que dans les cas fixés par la loi et ne peut avoir pour objet ni pour effet de pourvoir durablement à un emploi lié à l'activité normale et permanente de l'entreprise."
  },
  {
    id: 'conges-payes-art-231',
    intitule: "Droit et durée du congé annuel payé",
    domaine: 'droit_travail',
    valeurOuFormule: "1,5 jour de congé par mois de service (soit 18 jours ouvrables par an) après 6 mois de service continu",
    populationConcernee: "Salariés ayant accompli au moins 6 mois de service continu",
    dateDebutEffet: "2004-06-08",
    sourceExacte: "Code du Travail marocain (Loi 65-99), Articles 231 et suivants",
    dateConsultation: "2025-01-15",
    statutVerification: "verifiee_officielle",
    validationFormateur: true,
    descriptionDetaillee: "Augmentation de 1,5 jour de congé supplémentaire par période de 5 années de service, sans que le total puisse dépasser 30 jours de travail effectif."
  },
  {
    id: 'art-37-echelle-sanctions',
    intitule: 'Échelle des sanctions disciplinaires (faute légère)',
    domaine: 'droit_travail',
    valeurOuFormule: '1) Avertissement 2) Blâme 3) 2e blâme ou mise à pied ≤ 8 jours 4) 3e blâme, transfert ou rétrogradation — dans la même année',
    populationConcernee: 'Tous les salariés du secteur privé non agricole',
    dateDebutEffet: '2004-06-08',
    sourceExacte: 'Code du Travail marocain (Loi n° 65-99), Article 37',
    dateConsultation: '2026-10-05',
    statutVerification: 'verifiee_officielle',
    validationFormateur: true,
    descriptionDetaillee: "L'employeur ne peut infliger qu'une seule des sanctions de cette échelle par faute, de façon progressive, sur une période de 12 mois à compter de la première sanction."
  },
  {
    id: 'art-39-faute-grave',
    intitule: 'Fautes graves justifiant un licenciement sans préavis ni indemnité',
    domaine: 'droit_travail',
    valeurOuFormule: "Vol, abus de confiance, violence, divulgation d'un secret professionnel, faute ayant causé un dommage matériel considérable… (liste non exhaustive de l'Art. 39)",
    populationConcernee: 'Tous les salariés du secteur privé non agricole',
    dateDebutEffet: '2004-06-08',
    sourceExacte: 'Code du Travail marocain (Loi n° 65-99), Article 39',
    dateConsultation: '2026-10-05',
    statutVerification: 'verifiee_officielle',
    validationFormateur: true,
    descriptionDetaillee: "Une faute grave avérée, et une procédure régulière, dispensent l'employeur de l'indemnité de licenciement et de l'indemnité compensatrice de préavis."
  },
  {
    id: 'art-41-licenciement-abusif',
    intitule: 'Dommages-intérêts pour licenciement abusif',
    domaine: 'droit_travail',
    valeurOuFormule: "1,5 mois de salaire par année ou fraction d'année ≥ 6 mois d'ancienneté, plafonné à 36 mois de salaire",
    populationConcernee: 'Salarié licencié sans motif valable ou sans procédure régulière',
    dateDebutEffet: '2004-06-08',
    sourceExacte: 'Code du Travail marocain (Loi n° 65-99), Article 41',
    dateConsultation: '2026-10-05',
    statutVerification: 'verifiee_officielle',
    validationFormateur: true,
    descriptionDetaillee: "Le juge apprécie le caractère abusif du licenciement ; ce simulateur propose une estimation pédagogique, pas une décision judiciaire."
  },
  {
    id: 'art-43-preavis',
    intitule: 'Indemnité compensatrice de préavis',
    domaine: 'droit_travail',
    valeurOuFormule: 'Non-cadre : 8j (<1an) / 1 mois (1-5 ans) / 2 mois (>5 ans) — Cadre : 1 mois / 2 mois / 3 mois',
    populationConcernee: 'Salarié licencié sans faute grave retenue',
    dateDebutEffet: '2004-06-08',
    sourceExacte: 'Code du Travail marocain (Loi n° 65-99), Articles 43 et 51',
    dateConsultation: '2026-10-05',
    statutVerification: 'verifiee_officielle',
    validationFormateur: true,
    descriptionDetaillee: "Barème simplifié à des fins pédagogiques, dépendant de la catégorie professionnelle et de l'ancienneté du salarié."
  },
  {
    id: 'art-53-indemnite-licenciement',
    intitule: 'Indemnité légale de licenciement',
    domaine: 'droit_travail',
    valeurOuFormule: '96h × chacune des 5 premières années + 144h × (6e-10e année) + 192h × (11e-15e année) + 240h au-delà',
    populationConcernee: "Salarié licencié avec au moins 6 mois d'ancienneté, hors faute grave",
    dateDebutEffet: '2004-06-08',
    sourceExacte: 'Code du Travail marocain (Loi n° 65-99), Article 53',
    dateConsultation: '2026-10-05',
    statutVerification: 'verifiee_officielle',
    validationFormateur: true,
    descriptionDetaillee: "Le nombre d'heures de salaire dû par tranche d'ancienneté est multiplié par le taux horaire moyen du salarié."
  },
  {
    id: 'art-62-delai-procedure',
    intitule: 'Délais de la procédure de licenciement pour faute grave',
    domaine: 'droit_travail',
    valeurOuFormule: 'Entretien préalable sous 8 jours à compter de la constatation · Notification de la décision sous 48 heures après la décision',
    populationConcernee: 'Salarié visé par une procédure de licenciement pour faute grave',
    dateDebutEffet: '2004-06-08',
    sourceExacte: 'Code du Travail marocain (Loi n° 65-99), Article 62',
    dateConsultation: '2026-10-05',
    statutVerification: 'verifiee_officielle',
    validationFormateur: true,
    descriptionDetaillee: "Le non-respect de ces délais expose l'employeur à une requalification du licenciement en licenciement abusif."
  }
];
